"""Add items_quota to UserSettings

Revision ID: 549d40083a3d
Revises: 6eacb689f682
Create Date: 2025-07-06 21:45:20.579495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549d40083a3d'
down_revision = '6eacb689f682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coplist', schema=None) as batch_op:
        batch_op.drop_index('ix_coplist_user_id')

    op.drop_table('coplist')
    op.drop_table('coplist_items')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_quota', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('items_quota')

    op.create_table('coplist_items',
    sa.Column('coplist_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['coplist_id'], ['coplist.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('coplist_id', 'item_id')
    )
    op.create_table('coplist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_private', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coplist', schema=None) as batch_op:
        batch_op.create_index('ix_coplist_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
