"""Set purchase_date as non-nullable in Item model

Revision ID: a278a9811fc0
Revises: 70c95d2f10e2
Create Date: 2025-02-04 21:03:09.258727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a278a9811fc0'
down_revision = '70c95d2f10e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
